services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6161
      POSTGRES_DB: cloudprojectdb
    ports:
      - "5432:5432"
    # Burası veritabanının "Hard Diski" oluyor:
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: alperenyazici/cloudproject:latest
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cloudprojectdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 6161

# Docker'a bu diski oluşturmasını söylüyoruz:
volumes:
  postgres_data: